apiVersion: v1
kind: Secret
metadata:
  name: genzfashion-secrets
type: Opaque
stringData:
  mongodb-uri: "mongodb://admin:password@mongodb.genzfashion.svc.cluster.local:27017/genzfashiondb?authSource=admin"
data:
  db-username: YWRtaW4=  # base64 encoded 'admin'
  db-password: cGFzc3dvcmQ=  # base64 encoded 'password'
  