networks:
  gen_network:
    external: true

volumes:
  mongodb_data:
    driver: local

services:
  genzfashionapi:
    build:
      context: ./genZFashionAPI
      dockerfile: Dockerfile
    container_name: genzfashionapi
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - gen_network
    env_file:
      - ./genZFashionAPI/.env
    volumes:
      - ./genZFashionAPI:/app
      - /app/node_modules
    depends_on:
      - db

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: genzfashion_mongo_express
    ports:
      - "8000:8081"
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://db:27017/genZFashionDB"
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: "admin"
      ME_CONFIG_BASICAUTH_PASSWORD: "password123"
    restart: unless-stopped
    networks:
      - gen_network
    depends_on:
      - db

  db:
    image: mongo:noble
    container_name: genzfashion_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - gen_network

