apiVersion: v1
kind: Secret
metadata:
  name: {{ include "genzfashion-api.fullname" . }}-secret
  labels:
    {{- include "genzfashion-api.labels" . | nindent 4 }}
type: Opaque
data:
  MONGODB_URI: {{ .Values.secrets.mongoUri | b64enc }}