name: Helm Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Deploy to k3s
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: STS
        run: aws sts get-caller-identity

      - name: Deploy to k3s
        run: |
          # Read kubeconfig from repo secret and save to file
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          export KUBECONFIG=$(pwd)/kubeconfig

          kubectl get nodes
          helm list -A

          